language: python
python: 
  - 3.4
  - 3.5
  - 3.6
  - 3.7
  - 3.8
  - 3.8-dev
  - nightly 
cache: pip
install:
  pip install pytest-cov 
  pip install coveralls
script:
  - pytest --cov=src/
after_success:
   coveralls
